version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs:Z
      - ./cache:/app/cache:Z  # Add this line to share cache directory
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always
  
  worker:
    build: .
    command: celery -A tasks worker --loglevel=info --concurrency=1 --max-tasks-per-child=10
    volumes:
      - ./logs:/app/logs:Z
      - ./cache:/app/cache:Z
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  
  redis:
    image: docker.io/redis:alpine
    ports:
      - "6380:6379"
    restart: always